### ISSUE TITLE
Enable Round-Robin Scheduling

### ISSUE THREAD

**Issue by Cam0Cow** [lhr-solar/Controls#330]
OS_CFG_SCHED_ROUND_ROBIN_EN must be enabled, since we want to have tasks at the same priority level. More configuration might be necessary to get this to work.

**Comment by IshDeshpa** [comment]
Determined unnecessary for the time being since we explicitly define scheduling points in all of our tasks anyways. The only advantage to enabling round robin is the ability to set multiple tasks to the same priority and define time quanta for how long they can run, but since we have scheduling points defined everywhere the OS will automatically switch to another task at the same priority at that point, rather than after a time quanta.
