### ISSUE TITLE
Display is screwed up

### ISSUE THREAD

**Issue by IshDeshpa** [lhr-solar/Controls#424]
**Describe the bug**
- Gears are not displaying on the display properly.
- Velocity is not accurate to the car on the display
- Probably other issues as well

**Comment by aidenmadaffri** [comment]
m2-fix contains some temporary fixes to start trying to fix this.

**Comment by KnockbackNemo** [comment]
- Fixed an FSM issue, so the gears now change properly
- Queue doesn't seem to be filling up since the display can update gear state
- Velocity accuracy not yet tested, but this could also be done when retesting SendTritium on hardware
- Did not see any task errors thrown while running in production/M2
